<?php

return [
    'guest'=>[
        '',
        'categories/category\d{1,}',
        'login',
        'registration',
        'post\d{1,}',
        'api/login',
        'api/registration'
    ],
    'user'=>[
        '',
        'lk',
        'categories/category\d{1,}',
        'post\d{1,}',
        'api/logout',
        'posts',
        'posts/create',
        'posts/edit',
        'api/user/update',
        'api/user/changePassword',
        'api/posts/create',
        'api/posts/update',
        'api/posts/delete',
    ],
    'admin'=>[
        '',
        'lk',
        'categories/category\d{1,}',
        'post\d{1,}',
        'api/logout',
        'api/user/update',
        'api/user/changePassword',
        'admin/posts/create',
        'admin/posts/edit',
        'admin/posts/delete',
        'admin/city/create',
        'admin/city/edit',
        'admin/city/delete',
        'api/posts/create',
        'api/posts/update',
        'api/posts/delete',
        'api/city/create',
        'api/city/edit',
        'api/city/delete',
        'admin/migrate/fresh',
        'admin/migrate/freshAndSeed',
        'admin/migrate',
        'admin/migrateAndSeed'
    ]
];